name: Auto Merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  check_suite:
    types: [completed]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically merge Dependabot PRs
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: all # Specify which updates to auto-merge (patch, minor, major, all)
          github-token: "${{ secrets.GITHUB_TOKEN }}"
