name: Auto Merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event.label.name == 'dependencies'
    steps:
      - name: Auto merging PR
        uses: pascalgn/automerge-action@v0.14.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          mergeMethod: squash
          commitMessage: "chore: merge dependabot PR"
          labels: "dependencies,automerge" # Dependabot PRs must have these labels to be merged
