name: Auto Merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  check_suite:
    types: [completed]

permissions:  # This sets permissions for the GITHUB_TOKEN
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Enable auto-merge for Dependabot PRs
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          github-token: "${{ secrets.MY_PAT }}" 
          pull-request-number: 0
          label-filter: "dependencies"
          enable-for-draft-pr: false
